# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myQT.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(899, 635)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setMouseTracking(False)
        self.temp_val = QtWidgets.QLineEdit(Dialog)
        self.temp_val.setGeometry(QtCore.QRect(200, 110, 113, 33))
        self.temp_val.setObjectName("temp_val")
        self.refresh = QtWidgets.QPushButton(Dialog)
        self.refresh.setGeometry(QtCore.QRect(390, 530, 101, 31))
        self.refresh.setObjectName("refresh")
        self.cel_faran = QtWidgets.QPushButton(Dialog)
        self.cel_faran.setGeometry(QtCore.QRect(330, 110, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        self.cel_faran.setFont(font)
        self.cel_faran.setObjectName("cel_faran")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 131, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 460, 151, 31))
        self.label_4.setObjectName("label_4")
        self.time_req = QtWidgets.QLineEdit(Dialog)
        self.time_req.setGeometry(QtCore.QRect(180, 460, 231, 33))
        self.time_req.setObjectName("time_req")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(480, 110, 181, 21))
        self.label_5.setObjectName("label_5")
        self.hum_val = QtWidgets.QLineEdit(Dialog)
        self.hum_val.setGeometry(QtCore.QRect(680, 110, 113, 33))
        self.hum_val.setObjectName("hum_val")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(70, 170, 101, 21))
        self.label_9.setObjectName("label_9")
        self.avg_temp = QtWidgets.QLineEdit(Dialog)
        self.avg_temp.setGeometry(QtCore.QRect(200, 170, 113, 33))
        self.avg_temp.setObjectName("avg_temp")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 590, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(520, 170, 141, 21))
        self.label_10.setObjectName("label_10")
        self.avg_hum = QtWidgets.QLineEdit(Dialog)
        self.avg_hum.setGeometry(QtCore.QRect(680, 170, 113, 33))
        self.avg_hum.setObjectName("avg_hum")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(240, 30, 161, 21))
        self.label.setObjectName("label")
        self.sensor_stat = QtWidgets.QLineEdit(Dialog)
        self.sensor_stat.setGeometry(QtCore.QRect(430, 30, 231, 33))
        self.sensor_stat.setObjectName("sensor_stat")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 240, 191, 21))
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(460, 240, 191, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 370, 161, 21))
        self.label_7.setObjectName("label_7")
        self.hum_level = QtWidgets.QProgressBar(Dialog)
        self.hum_level.setGeometry(QtCore.QRect(700, 370, 118, 23))
        self.hum_level.setProperty("value", 0)
        self.hum_level.setFormat("%p%")
        self.hum_level.setObjectName("hum_level")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(500, 370, 161, 21))
        self.label_8.setObjectName("label_8")
        self.temp_alarm = QtWidgets.QSlider(Dialog)
        self.temp_alarm.setGeometry(QtCore.QRect(220, 240, 160, 26))
        self.temp_alarm.setMinimum(10)
        self.temp_alarm.setMaximum(30)
        self.temp_alarm.setOrientation(QtCore.Qt.Horizontal)
        self.temp_alarm.setObjectName("temp_alarm")
        self.hum_alarm = QtWidgets.QSlider(Dialog)
        self.hum_alarm.setGeometry(QtCore.QRect(680, 240, 160, 26))
        self.hum_alarm.setMinimum(5)
        self.hum_alarm.setOrientation(QtCore.Qt.Horizontal)
        self.hum_alarm.setObjectName("hum_alarm")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(270, 280, 67, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(720, 280, 67, 21))
        self.label_12.setObjectName("label_12")
        self.temp_level = QtWidgets.QProgressBar(Dialog)
        self.temp_level.setGeometry(QtCore.QRect(220, 370, 118, 23))
        self.temp_level.setProperty("value", 0)
        self.temp_level.setObjectName("temp_level")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(510, 450, 71, 31))
        self.label_13.setObjectName("label_13")
        self.alarm = QtWidgets.QLineEdit(Dialog)
        self.alarm.setGeometry(QtCore.QRect(602, 450, 221, 33))
        self.alarm.setObjectName("alarm")

        self.retranslateUi(Dialog)
        self.temp_alarm.valueChanged['int'].connect(self.label_11.setNum)
        self.hum_alarm.valueChanged['int'].connect(self.label_12.setNum)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TEMPERATURE & HUMIDITY SENSOR ANALYSIS"))
        Dialog.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TEMPERATURE/HUMIDITY SENSOR READING</span></p></body></html>"))
        Dialog.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.refresh.setText(_translate("Dialog", "REFRESH"))
        self.cel_faran.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">F/C</span></p></body></html>"))
        self.cel_faran.setText(_translate("Dialog", "F/C"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">TEMP VALUE  :</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">REQUEST TIME :</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">HUMIDITY VALUE :</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">AVG TEMP :</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Dialog", "CLOSE"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">AVG HUMIDITY:</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">SENSOR STATUS:</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">SET TEMP ALARM:</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">SET HUM ALARM:</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">THERMOMETER:</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">HUMIDITY LEVEL:</span></p></body></html>"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#00007f;\">VALUE</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#00007f;\">VALUE</span></p></body></html>"))
        self.temp_level.setFormat(_translate("Dialog", "%p"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">ALARM:</span></p></body></html>"))

