# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myQT.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(899, 635)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Dialog.setMouseTracking(False)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(430, -40, 16, 641))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 10, 191, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(590, 10, 151, 31))
        self.label_2.setObjectName("label_2")
        self.temp_val = QtWidgets.QLineEdit(Dialog)
        self.temp_val.setGeometry(QtCore.QRect(200, 50, 113, 33))
        self.temp_val.setObjectName("temp_val")
        self.temp_refresh = QtWidgets.QPushButton(Dialog)
        self.temp_refresh.setGeometry(QtCore.QRect(170, 250, 101, 31))
        self.temp_refresh.setObjectName("temp_refresh")
        self.cel_faran = QtWidgets.QPushButton(Dialog)
        self.cel_faran.setGeometry(QtCore.QRect(370, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        self.cel_faran.setFont(font)
        self.cel_faran.setObjectName("cel_faran")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 50, 131, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 151, 31))
        self.label_4.setObjectName("label_4")
        self.time_req_temp = QtWidgets.QLineEdit(Dialog)
        self.time_req_temp.setGeometry(QtCore.QRect(180, 140, 231, 33))
        self.time_req_temp.setObjectName("time_req_temp")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(470, 50, 181, 21))
        self.label_5.setObjectName("label_5")
        self.hum_val = QtWidgets.QLineEdit(Dialog)
        self.hum_val.setGeometry(QtCore.QRect(670, 50, 113, 33))
        self.hum_val.setObjectName("hum_val")
        self.time_req_hum = QtWidgets.QLineEdit(Dialog)
        self.time_req_hum.setGeometry(QtCore.QRect(640, 150, 231, 33))
        self.time_req_hum.setObjectName("time_req_hum")
        self.hum_refresh = QtWidgets.QPushButton(Dialog)
        self.hum_refresh.setGeometry(QtCore.QRect(620, 250, 101, 31))
        self.hum_refresh.setObjectName("hum_refresh")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(460, 150, 151, 31))
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 280, 901, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(110, 360, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(540, 360, 256, 192))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(190, 310, 91, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(620, 310, 121, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(90, 90, 101, 21))
        self.label_9.setObjectName("label_9")
        self.avg_temp = QtWidgets.QLineEdit(Dialog)
        self.avg_temp.setGeometry(QtCore.QRect(200, 90, 113, 33))
        self.avg_temp.setObjectName("avg_temp")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(0, 590, 901, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(300, 600, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 600, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(490, 100, 141, 21))
        self.label_10.setObjectName("label_10")
        self.avg_hum = QtWidgets.QLineEdit(Dialog)
        self.avg_hum.setGeometry(QtCore.QRect(670, 100, 113, 33))
        self.avg_hum.setObjectName("avg_hum")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TEMPERATURE & HUMIDITY SENSOR ANALYSIS"))
        Dialog.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">TEMPERATURE/HUMIDITY SENSOR READING</span></p></body></html>"))
        Dialog.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#000091;\">TEMPERATURE</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">HUMIDITY</span></p></body></html>"))
        self.temp_refresh.setText(_translate("Dialog", "REFRESH"))
        self.cel_faran.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">F/C</span></p></body></html>"))
        self.cel_faran.setText(_translate("Dialog", "F/C"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">TEMP VALUE  :</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">REQUEST TIME :</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">HUMIDITY VALUE :</span></p></body></html>"))
        self.hum_refresh.setText(_translate("Dialog", "REFRESH"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">REQUEST TIME :</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#00007f;\">TEMP PLOT</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#00007f;\">HUMIDITY PLOT</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">AVG TEMP :</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "APPLY"))
        self.pushButton_3.setText(_translate("Dialog", "CLOSE"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#00007f;\">AVG HUMIDITY:</span></p></body></html>"))

